defaults: &defaults
  docker:
    - image: circleci/golang:1.13
  working_directory: /go/src/github.com/morikuni/failure

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: test
          command: make test
      - run:
          name: coverage
          command: make cover
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
